export const courseMetaData =  [
    {
        id: 1,
        coverImg: 'mountain-bike 1.png',
        title: 'Life Lessons With Katie Zaferes',
        description: 'React is one of the most popular front-end JavaScript libraries for building user interfaces.',
        stats: {
            rating: 5.0,
            reviewCount: 6,
        },
        price: 136,
        country: 'USA',
        location: 'ONLINE',
        openSpots: 0,
    },
    {
        id: 2,
        coverImg: 'image 12.png',
        title: 'Group Mountain Biking',
        description: 'After completing this course, you will be able to build web apps in modern React, using patterns like functional components and hooks.',
        stats: {
            rating: 4.8,
            reviewCount: 2,
        },
        price: 50,
        country: 'USA',
        location: 'ONLINE',
        openSpots: 27,
    },
    {
        id: 3,
        coverImg: '',
        title: 'Learn Wedding Photography',
        description: 'Learn React by building eight real-world projects and solving 140+ coding challenges.',
        stats: {
            rating: 5.0,
            reviewCount: 30,
        },
        price: 125,
        country: 'USA',
        location: 'OFFLINE',
        openSpots: 7,
    },
    {
        id: 4,
        coverImg: '',
        title: 'Barbar Group',
        description: 'After this you will be able to build web apps in modern React.',
        stats: {
            rating: 3.8,
            reviewCount: 72,
        },
        price: 192,
        country: 'USA',
        location: 'HYBRID',
        openSpots: 47,
    },
]

export const travelJournalMetaData = [
    {
        id: 1,
        isVerified: false,
        isFavourite: false,
        title: "Mount Fuji",
        location: "JAPAN",
        googleMapsUrl: "https://goo.gl/maps/HT3LDoptc5MFqkKb6",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
        imageUrl: "https://source.unsplash.com/WLxQvbMyfas",
    },
    {
        id: 2,
        isVerified: true,
        isFavourite: false,
        title: "Sydney Opera House",
        location: "AUSTRALIA",
        googleMapsUrl: "https://goo.gl/maps/CBQaLnWftDMJRZx79",
        startDate: "27 May, 2021",
        endDate: "8 Jun, 2021",
        description: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
        imageUrl: "https://source.unsplash.com/JmuyB_LibRo",
    },
    {
        id: 3,
        isVerified: false,
        isFavourite: true,
        title: "Geirangerfjord",
        location: "NORWAY",
        googleMapsUrl: "https://goo.gl/maps/e9sg3ErquzGZxWiu5",
        startDate: "01 Oct, 2021",
        endDate: "18 Nov, 2021",
        description: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
        imageUrl: "https://source.unsplash.com/3PeSjpLVtLg",
    }
]